version: '3'

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"  # Only if you want to use AdGuard Home as a DHCP server
      - "68:68/udp"  # Only if you want to use AdGuard Home as a DHCP server
      - "80:80/tcp"
      - "443:443/tcp"
      - "853:853/tcp"  # DNS-over-TLS
      - "3000:3000/tcp"  # Web interface
    volumes:
      - /data/adguard-home/work:/opt/adguardhome/work  
      - /data/adguard-home/confdir:/opt/adguardhome/conf
    restart: unless-stopped
