version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nextcloud/html:/var/www/html
      - /data/nextcloud/config:/etc/nextcloud
      - /data/nextcloud/apps:/var/www/html/custom_apps
      - /data/nextcloud/data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=changeme
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - /data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
