version: '3'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    ports:
      - 8123:8123
    volumes:
      - /data/homeassistant:/config
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped
